### ISSUE TITLE
When checking someone else's stats it says "Here are your stats for this server!"

### ISSUE THREAD

**Issue by russhh** [benslv/countable#44]
A bug when bot's reply doesn't match the requested user. 
![image](https://user-images.githubusercontent.com/56453212/121192425-9ca94580-c875-11eb-858e-80a56ea080c9.png)

**Comment by benslv** [comment]
Given how the code for this is implemented, I can't really make it say either "Here are your stats" or "Here are the stats for this user" depending on the arguments provided without making a sizeable change to the command execution

**Comment by benslv** [comment]
Thinking it could work to just change it to, "Here are the stats for this user!"

What do you think?

**Comment by russhh** [comment]
I think that sounds good. If it is possible you could maybe look into making it "Here are {requested user}'s stats!"

**Comment by benslv** [comment]
That would be quite quick to implement, yeah!

**Comment by benslv** [comment]
Complete now!
