### ISSUE TITLE
Logic error in stats command

### ISSUE THREAD

**Issue by Sciencentistguy** [benslv/countable#45]
The checkArgs function for the stats command is incorrect.

https://github.com/benslv/countable/blob/5e2cb6b3c42156d0cd6f868cdf88668508f72475/src/commands/stats.js#L6

This is parsed as `0 <= (args.length <= 1)`. I presume this is not the intended behavior.

**Comment by benslv** [comment]
I was hoping that would work as meaning "between 0 and 1 arguments provided (inclusive) but I didn't test it 😁

**Comment by Sciencentistguy** [comment]
One of the many classes of issues that's exposed at compile time by strong typing :)

**Comment by Sciencentistguy** [comment]
This was fixed in #46
