### ISSUE TITLE
I Can't Invite the Bot

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [benslv/countable#70]
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/72280887/151852434-022cb8e3-2605-446e-b3c3-147e7dd0dbbb.png">
i just can't invite it

**Comment by benslv** [comment]
Hey, sorry to hear that! Could you try [this link](https://discord.com/login?redirect_to=%2Foauth2%2Fauthorize%3Fclient_id%3D740570057297362995%26scope%3Dbot%26permissions%3D268790864)?

**Comment by benslv** [comment]
It looks like it doesn't work if you have `https://` at the start which...isn't great. I'll look into fixing that.

**Comment by jkvhjggfhjyhgggh** [comment]
yes tysm it works

**Comment by benslv** [comment]
Glad to hear it! Hope you enjoy!
